config/routes.rb
Rails.application.routes.draw do
  resources :sessions
  get "sign_up" => "users#new", :as => "sign_up"
  resources :users
  post 'articles/process_file', as: :pfil
  get 'articles/upload', as: :upl
  get 'articles/export', as: :exp
  resources :comments
  resources :images
  resources :articles
  root :to => "articles#index"
  namespace :api do
    resources :becaks
  end
  resources :bycycles do
    member do
      get 'special'
      post 'discount'
    end
    collection do
      get 'abc'
      post 'def'
    end
  end
  get 'bycycles/:id/buy' => 'bycycles#buy',as: :buy

end

app/models/article.rb
class Article < ActiveRecord::Base
  mount_uploader :file, ImageUploader
  validates :title, presence: true,
            length: { minimum: 5 }
  validates :content, presence: true,
            length: { minimum: 10 }
  validates :status, presence: true
  scope :status_active, -> {where(status: 'active')}
  #default_scope {where(status: 'active')}

  #relationship
  has_many :comments, dependent: :destroy
end

app/controllers/articles_controller.rb
require 'roo'
class ArticlesController < ApplicationController
  before_action :check_current_user, only: [:new, :create, :edit, :update, :destroy]
  def index
    #@articles = Article.all
    @articles = Article.paginate(:page => params[:page], :per_page => 3)
    #@articles = Article.status_active 
  end

  def export
    @articles = Article.all
    respond_to do |format|
      format.xlsx
    end
  end

  def process_file
    #debugger
    raise 'Nothing to import' unless params[:file].present?

    total_row = 0
    spreadsheet = open_spreadsheet(params[:file])

    spreadsheet.sheets.each_with_index do |sheet, index|
      spreadsheet.default_sheet = spreadsheet.sheets[index]

      header = Array.new
      spreadsheet.row(1).each { |row| header << row.downcase.tr(' ', '_') }
      (2..spreadsheet.last_row).each do |i|
        row = Hash[[header, spreadsheet.row(i)].transpose]
        new_row = eval("#{spreadsheet.default_sheet.singularize}").new(row)

        # Check existance on database, if the record already exist, destroy it with it's comment
        checker = eval("#{spreadsheet.default_sheet.singularize}").find(row['id'].to_i) rescue nil
        checker.destroy unless checker.nil?

        raise 'Failed to save, maybe invalid column' unless new_row.save!

        total_row += 1
      end
    end

    respond_to do |f|
      f.html { redirect_to articles_path, :notice => "Importing #{total_row} records successfully" }
    end
  end

  def open_spreadsheet(file)
    case File.extname(file.original_filename)
      when '.csv' then Roo::Csv.new(file.path, nil, :ignore)
      when '.xls' then Roo::Excel.new(file.path, nil, :ignore)
      when '.xlsx' then Roo::Excelx.new(file.path, nil, :ignore)
      else raise "Unknown file type: #{file.original_filename}"
    end
  end
   
  def new
    @article = Article.new
  end

  def show
    @article = Article.find_by_id(params[:id])
    #@comments = Article.find_by_id(params[:id]).comments
    @comments = @article.comments.order("id desc")
    @comment = Comment.new
  end

  def edit
    @article = Article.find_by_id(params[:id])
  end

  def create
    @article = Article.new(params_article)
    if @article.save
    flash[:notice] = "Success Add Records"
    #redirect_to action: 'index'
    redirect_to root_path
    else
      flash[:error] = "data not valid"
      render 'new'
    end
  end

  def update
    @article = Article.find_by_id(params[:id])

    if @article.update(params_article)
    flash[:notice] = "Success Update Records"
    redirect_to action: 'index'
    else
      flash[:error] = "data not valid"
      render 'edit'
    end
  end

  def destroy
    @article = Article.find_by_id(params[:id])

    if @article.destroy
    flash[:notice] = "Success Delete Records"
    redirect_to action: 'index'
    else
      flash[:error] = "fails delete a records"
      render 'edit'
    end
  end

  def params_article
    params.require(:article).permit(:title, :content, :status)
  end

end

app/views/articles/_comments.html.erb
<% @comments.each do |comment| %>
  <p>
  <b> 
    <%= comment.user.try(:username)  %>
  </b>
  </p>
  <br>
  <%= comment.content %>
<% end %>

app/views/articles/_form.html.erb
<%= form_for @comment, url: comments_path, remote: true do |f| %>
  <%= f.hidden_field :article_id, value: @article.id %>
  <% if current_user %>
    <%= f.hidden_field :user_id, value: current_user.id %>
  <% end %>
  <br>
  <%= f.label :content  %>
  <%= f.text_area :content, cols: 20, rows: 10 %>
  <br>
  <%= f.submit :submit  %>
<% end %>

app/views/articles/edit.html.erb
<%= form_for @article do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
<br>
<%= f.label :content %>
<%= f.text_area :content, cols: 20, rows: 10 %>
<br>
<%= f.label :status %>
<%= f.radio_button :status, "active" %>
<%= label :article_status, 'active' %>
<%= f.label :article_status, 'off' %>
<br>
<%= f.submit :submit %>
<% end %>

app/views/articles/index.html.erb
<h2>
  <% if !current_user %>
    <%= link_to 'Log-in', new_session_path %>
  <% else %>
  Hello <%= current_user.username %>
<%= link_to 'Logout', session_path(current_user.id), method: "DELETE" %>
<% end %>
</h2>

<% @articles.each do |article| %>
  <h3> <%= article.title %> </h3>
  <p> <%= article.content.truncate(20)%> </p>
  <%= link_to 'read more', article_path(article.id) %> 
  <h4> status: <%= article.status %> </h4>
  <p>
  <span> <%= link_to 'edit', edit_article_path(article.id) %> </span>
  <span>|</span>
  <span> <%= link_to 'delete', article_path(article.id), method: "DELETE", data: {confirm: 'Delete this data? '} %> </span>
  </p>
  <hr>
<% end %>
<%= will_paginate @articles , renderer: BootstrapPagination::Rails %>

app/views/articles/new.html.erb
<%= form_for @article do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title  %>
  <%= @article.errors[:title].first unless @article.errors[:title].blank? %>
  <br/>  
  <%= f.label :content  %>
  <%= f.text_area :content, cols: 20, rows: 10  %>
  <%= @article.errors[:content].first unless @article.errors[:content].blank? %>
  <br/>  
  <br/>  
  <%= f.label :status %>
  <%= f.radio_button :status, "active"  %>
  <%= f.radio_button :status, "off", :checked => true  %>
  <%=label :article_status, 'off'  %>
  <br/>  
  <%= f.submit :submit %>
<% end  %>

app/views/articles/show.html.erb
<div class="page-header"><h3> <%= @article.title %> </h3></div>
<p> <%=@article.content %> </p>
<p> <%=link_to raw("<span class='glyphicon glyphicon-save' aria-hidden='true'></span>"), exp_path(format: 'xlsx') %> </p>
<p> <%=link_to 'back to index', articles_path %> </p>
<hr>
<div id="form-comment">
  <%= render "form" %>
</div>
<h4>Here the comments</h4>
<div id="list-comments">
  <%= render "comments" %>
</div>

app/views/articles/upload.html.erb
<%= form_tag :pfil, multipart: true do  %>
  <%= label_tag "file" %>
  <%= file_field_tag :file  %>
  <br/>  
  <%= submit_tag :submit %>

<% end  %>