config/routes.rb
Rails.application.routes.draw do
  resources :sessions
  get "sign_up" => "users#new", :as => "sign_up"
  resources :users
  post 'articles/process_file', as: :pfil
  get 'articles/upload', as: :upl
  get 'articles/export', as: :exp
  resources :comments
  resources :images
  resources :articles
  root :to => "articles#index"
  namespace :api do
    resources :becaks
  end
  resources :bycycles do
    member do
      get 'special'
      post 'discount'
    end
    collection do
      get 'abc'
      post 'def'
    end
  end
  get 'bycycles/:id/buy' => 'bycycles#buy',as: :buy

end

app/models/image.rb
require 'file_size_validator'
class Image < ActiveRecord::Base
  mount_uploader :url, ImageUploader
  #validates :url, :file_size => { :maximum => 200.kilobytes.to_i }
  #validate :image_size_validation, :if => "url:"
  validates :url, 
    :presence => true, 
    :file_size => { 
      :maximum => 0.2.megabytes.to_i 
    } 
  #def image_size_validation
     #if url.size > 200.kilobytes
       #errors.add(:base, "Image should be less than 200 kb")
     #end
  #end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  def index
    @images = Image.all
  end

  def new
    @image = Image.new
  end

  def create
      @image = Image.new(params_image)
      if @image.save
      flash[:notice] = "Success Add Records"
      redirect_to action: 'index'
      else
        flash[:error] = "data not valid"
        render 'new'
      end
  end

  def update
    @image = Image.find_by_id(params[:id])
  
    if @image.update(params_image)
      flash[:notice] = 'Image was successfully updated.'
      redirect_to action: 'index'
    else
      flash[:error] = 'Image not valid'
      render 'edit'
    end 
  end

  def destroy
    @image = Image.find(params[:id])
    if @image.destroy
      flash[:notice] = "Deleted"
      redirect_to action: 'index'
    else
      flash[:notice] = "fails delete a records"
      render 'edit'
    end 
  end

  def edit
    @image = Image.find_by_id(params[:id])
  end

  def show
    @image = Image.find_by_id(params[:id])
  end

  def params_image
    params.require(:image).permit(:title, :url, :description)
  end

end

app/helpers/images_helper.rb
module ImagesHelper
end

app/views/images/edit.html.erb
<%= form_for @image, multipart: true do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title, class: "form-control"  %>
  <%= @image.errors[:title].first unless @image.errors[:title].blank? %>
  <br/>
  <%= f.label :url %>
  <%= f.file_field :url  %>
  <%= @image.errors[:url].first unless @image.errors[:url].blank? %>
  <%= @image.errors[:url].first unless @image.errors[:url].blank? %>
  <br/>  
  <%= f.label :description  %>
  <%= f.text_area :description, cols: 20, rows: 10, class: "form-control" %>
  <%= @image.errors[:description].first unless @image.errors[:description].blank? %>
  <br/>  
  <%= f.submit :submit %>

<% end  %>

app/views/images/index.html.erb
  <div class="masonry-container">
  <% @images.each do |image| %>
    <div class="col-md-2 item">
      <div class="panel panel-default">
        <%= link_to image, :data => { :toggle => 'modal', :target => '#modal' } do %>
          <div class="panel-heading text-center">
              <%= image_tag image.url_url(:thumb_large), :class => 'img-responsive' %>
          </div>
        <% end %>
        <div class="panel-body">
          <strong><%= image.title %></strong>
          <br>
          <%= image.description %>
        </div>
        <div class="panel-footer">
          <div class="text-right">
            <%= link_to edit_image_path(image) do %>
              edit
            <% end %>
            <%= link_to image, method: :delete, data: { confirm: 'Are you sure?' } do %>
              delete
            <% end %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/images/new.html.erb
<%= form_for @image, multipart: true do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title, class: "form-control"  %>
  <%= @image.errors[:title].first unless @image.errors[:title].blank? %>
  <br/>
  <%= f.label :url %>
  <%= f.file_field :url  %>
  <%= @image.errors[:url].first unless @image.errors[:url].blank? %>
  <%= @image.errors[:url].first unless @image.errors[:url].blank? %>
  <br/>  
  <%= f.label :description  %>
  <%= f.text_area :description, cols: 20, rows: 10, class: "form-control" %>
  <%= @image.errors[:description].first unless @image.errors[:description].blank? %>
  <br/>  
  <%= f.submit :submit %>

<% end  %>